language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: mx9RPwon2DvrkPPfClHWqgEqiW3H9UCCndd6nwQSi7NFDhpuPnhb5Ds7WrzsxSP+2ZRhEPmgVBulDNC661I+AgH/P2moxzhqLQ5yZXU69+APfaiIImfWBdvvq90b/rdAHmBj603aNnJ3U8RwmSLe3ecYae5eJzgjMJ2r6XAu7TsFz5PgRPnBzC4lUzyg7JD2RmJ2YZKJ4kj9qIF5tyNvDIbhlpIU9hdmhGLGCb+w1QK+DdnGdIArCR6kH6L1DB4XpKhntPe1zdXU/Iu39QRCr4yuj51FYorXdw4FpaQHWNUOqmMWs1z/b8FvHVdF8HC/78OXegj6/atrb/e17CUucA9KV8Pu4Wv/cucOvRobouZlsBMPNxtKecPRhGA4asPB1/rfWkQvV4kF8TcffCg45GGETFxlkwlrD+ZxQe9PErcGpeJk21FRxDdCqNOSVE8sHD46uj3D3tU3ZVGeXzYpOpKSXhND4vdNeeIBaTWU64GFB0taLRblAbTLTd5oU+DUTtdx4iUhWnI1kFWHoyCkNr8EQaT+uGyYQfkdbzimWsb7KfKcF3fH2aeHo4+whfZqU97H0esZNWX8Cqw9iifhcgC/CdwaBZuGwltyJivMOWJIhvVUF7+fOPD/sGiMhRSbbzukPvCT8scMlY3i2/a42JqBw7JGIMC16lHBKDph8Sk=
  - secure: D4xxXSIUqGPyKuyzCg51ryrptyGgmVa7PFQ0lNl8Uz6+g+BZNuMwFmBKAd4Z+c1vaQgZEUKzksapYtctq96u6+0uDCSz9buGhwCmR17u58T4HsGQ4c47IFHqYoNEdKZAU5mYsQGLtdXG+Ls8CXAjSogc29M4xToGTFcJAWw8f0BbRUMfOcTYsT6PFPi6YxBHHwaR+FWm4CirSgOhD79QxwXbGFkX/C1GvgQ9MO+5xJH+izxWV8wK/4um3KZtHgzisSyjwsh4n4R7fLWlCcIpL7sxBahs0LSlQqIgy/zRBUxE6hvGLbxfn0HDrggOy8Ro4x+alCLeOkirNr/yHM1/XlTx7apsqOiO61+xT0Uf5XQaM0T/1O99PvuOp0uHbIazCGIOhTKndeWyPV8KZGVC1chhHmEziI5+e5F5GcoKgpxB674bYrKeP3j4qs5UYzJmMKpyEK865BBHbty5Tu/LZ9mOjCj1kQ96f+sxqN5TCuBbnhdye4gO7BM2QQLPy7Bb5TZrteHZkexkv3ZskREnz9tT/lBiZc6QHCC06k4vw5mKpMUlfXoTHVdYCnvn4KDJmg+nuPRHeXJrvYWCTizBxM0PD0/9fjOIYAXlPvHsyAQ0qQl4oc0DpCTa+v+Ag62waIF6OYvhaddGRLNNTsxyHNw7dfSBPwwBKO9yOEEUyms=
  - secure: W7t0BPsc7ZI2ZoAKTIG8pS5ziIJ2d1ghR8HBMZar3hrHG0knXjGYjhWUZsLJ3FMHYh+x31qSW5lqX7j7ViErReNFSGfnjDimnJoidwflJtc8G20uvvIqra0FC7IzHcuV6YRvvPJ3DD+LlQJsx9GYv+co/5xWpIpRZeKOzaJvvZOOBKl0aAGh4bJYMQPpBMpYsH6MZdw3PEvyrDEZRQWD21Sd5pe5C0TwYuWJJmTMNsimQELwFy3NOS17FUwsRudbwa93jTL73ubpyWQUsiGuXFjeC+XGzWPUidP0bN3bG6iR9o2fe4E5pTsJW4m4i8OPLWMJ7Wuy6lWXaEpACfu/NVNntEIQX50wa1OcQczxuxi/j1j6irFPo6QUkZ2+pqph3ScDJdFqSXxXWuEsC6Y4FqU8p9CgyNMrTSeNTbYESD5HCHlWfzZSg73QO9oUsGdoTGdfgwgNqBFIBiB1L+Bogqu0D9iMm6ltrU4o40Ju7nU1BMe/rD68mSxI+3IUKH/SY4oKaMoSbMP9LVkQtn1GD5boAJE+L/+b3OZLyb/NpsKQJ3MQwe5Ez6ycEV8fEYQX0T6WXa0Au3Bp0WPfF1X3SfQuym6uKG/y+qdGmOF2aixhZ6AmGYdz1ZhkazshB+mxzp7RwxXbreGCmAVAFAS9n/NWeLKig0ecKAam1E9YtDU=
before_install:
- export TZ=Pacific/Noumea
install: mvn install -DSkipTests=true -Dmaven.javadoc.skip=true -DcreateChecksum=true
script:
- mvn versioneye:update test jacoco:report
after_success:
- mvn coveralls:report
before_deploy:
- export RELEASE_PKG_FILE=$(ls target/*.war)
- export RELEASE_PKG_MD5_FILE=$(ls target/*.war.md5)
- export RELEASE_PKG_SHA_FILE=$(ls target/*.war.sha1)
- echo "deploying $RELEASE_PKG_FILE , $RELEASE_PKG_MD5_FILE , $RELEASE_PKG_SHA_FILE
  to GitHub releases"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: aeRnDCP3jdIltOaCR1rjocxtZ9aSzuIPbV6OSNfiNch1XNvHdkTuY9PYcB2U2JgkCKCKp9eQ36cgpi+72jIpLi9U/b92uID5XfgoUSoMB9RqClzUC6DXSpQcAUSIHBafESJzUetZ/5FOP3MdPbjj0PUqTTfaVECG1X6dg0pi5gmMIa3gsB7F5aZOcArfF0uXLJIZYdBAp/u9w1HoLAYaepql+yWuNebFZwQKdcM3aRERJ6hVQF+IeNEGfs5OLRNp2H6NiKnYT5g2nWNCdjOfvsOKDxDdlI4Ye5u3UQYIv2LbqyvXTDsrfRN4jo/W6WnMPr6oM5djUfccE0uhr36tTUV1LK98lVtfk3emALQvlQC4WyshGQUUAEGcfV6FTPslwVcRo+dYkUvPpNgSBqziMaSaKSa6SjYIvfWG94+xVOLOhWbZxvqe/3J05SWljlrtunEAADQE/UkRTUg9QCPbCWTKbtbLMuBCYUwFATUCkLF6o8kaf2dyYf0UNCc8kofrhpl9jXA4TwonNrWbB7yD00df92McFmk+BK2w7c/cJeMcRTZivLrzneCR0/FdpQBkF5o1GkiZH7164dKsOYqW6XUEgI9gvxwMsLJarep6OH39B901w6C04sQoxl66ZaI6ARlcscKY+hpB+UXhZNQDQtM6tbbakbG81y6iHBxGSdo=
  file:
  - "${RELEASE_PKG_FILE}"
  - "${RELEASE_PKG_MD5_FILE}"
  - "${RELEASE_PKG_SHA_FILE}"
  on:
    tags: true
    repo: DSI-Ville-Noumea/sirh
notifications:
  slack:
    secure: WoxKrEosY1E4ECd7/ce90mtefiEEGDX8XIxBR7qAw8oEFsMOqoF0Iq8xMf/CtdECFlmSP0rVZdHRsEDu3mbVLpUSQ6jDjFzgZWO8KJmIulQSAuv6FPjyRI9nLUgMk59aJOtZl+SqfbWMEFEc8kgC6/oeTdAlUJzLIqWMAH8bDl4apWB+g6lHWX8y2uDs5ykO7vwBBWUPCVYprbd15LuppYTxunDJv3HjNUqVycJPoFnSclWV7Ly+gnqZZjkHpuNIQbi0AFG+ghkv371LTaCBRf++BbJQH5506IhNzhZ0MqS8ek3ZnQ2qhLSTB17uu1bsjnrQ3ePp32naJCNv0k9CUu5Pi0wS4x7suGD5H4zEML//bXz3n7Z48UWDCjh88no9omjs8XhyVlnF8kTRcesCbb16ZVJl3S/lPibhKTCYRXu38abDQHoE8jH+oQ7AT2xVEjjRrRln8kzqjW5pjKB9Diw7zltfbUfNVxiA/cRWR+AihaCCQ983ugQWq0UiQONXidPfJ9gJWO78OQ2jK1RvfYNhN0zOt2s/5vRf6TW/70xgUjdnxcPUoPjTWZ85+hDkfn5wKnXZGWx/4UGH52ch39uO88CxNdfnHfsMB+UP/1ElS2WwKQtCeL3O1KKxtN7w1MND734qv/siY2zi2gKQuwFrwr/PQd5INdyqvg54Zqg=
