ALTER TABLE MAIRIE.SICDPO 
	ADD CONSTRAINT MAIRIE.Q_MAIRIE_SICDPO_CDCPOS_00001 
	PRIMARY KEY( CDCPOS , CODCOM ) ; 
  
ALTER TABLE MAIRIE.SICOMM 
	ADD CONSTRAINT MAIRIE.Q_MAIRIE_SICOMM_CODCOM_00001 
	PRIMARY KEY( CODCOM ) ; 
  
ALTER TABLE MAIRIE.SIGUIC 
	ADD CONSTRAINT MAIRIE.Q_MAIRIE_SIGUIC_CDBANQ_00001 
	PRIMARY KEY( CDBANQ , CDGUIC ) ; 
  
ALTER TABLE MAIRIE.SILIEU 
	ADD CONSTRAINT MAIRIE.Q_MAIRIE_SILIEU_CDLIEU_00001 
	PRIMARY KEY( CDLIEU ) ; 
  
ALTER TABLE MAIRIE.SIVIET 
	ADD CONSTRAINT MAIRIE.Q_MAIRIE_SIVIET_CODPAY_00001 
	PRIMARY KEY( CODPAY , SCODPA ) ; 
  
ALTER TABLE MAIRIE.SIVOIE 
	ADD CONSTRAINT MAIRIE.Q_MAIRIE_SIVOIE_CDVOIE_00001 
	PRIMARY KEY( CDVOIE ) ; 
  
ALTER TABLE MAIRIE.SPADMN 
	ADD CONSTRAINT MAIRIE.Q_MAIRIE_SPADMN_NOMATR_00001 
	PRIMARY KEY( NOMATR , DATDEB ) ; 
  
ALTER TABLE MAIRIE.SPBHOR 
	ADD CONSTRAINT MAIRIE.Q_MAIRIE_SPBHOR_CDTHOR_00001 
	PRIMARY KEY( CDTHOR ) ; 
  
ALTER TABLE MAIRIE.SPCARR 
	ADD CONSTRAINT MAIRIE.Q_MAIRIE_SPCARR_NOMATR_00001 
	PRIMARY KEY( NOMATR , DATDEB ) ; 
	
ALTER TABLE MAIRIE.SPCHGE 
	ADD CONSTRAINT MAIRIE.Q_MAIRIE_SPCHGE_NOMATR_00001 
	PRIMARY KEY( NOMATR , NORUBR , DATDEB ) ; 
  
ALTER TABLE MAIRIE.SPCLAS 
	ADD CONSTRAINT MAIRIE.Q_MAIRIE_SPCLAS_CODCLA_00001 
	PRIMARY KEY( CODCLA ) ; 
  
ALTER TABLE MAIRIE.SPECHE 
	ADD CONSTRAINT MAIRIE.Q_MAIRIE_SPECHE_CODECH_00001 
	PRIMARY KEY( CODECH ) ; 
  
ALTER TABLE MAIRIE.SPGENG 
	ADD CONSTRAINT MAIRIE.Q_MAIRIE_SPGENG_CDGENG_00001 
	PRIMARY KEY( CDGENG ) ; 
  
ALTER TABLE MAIRIE.SPGRADN 
	ADD CONSTRAINT MAIRIE.Q_MAIRIE_SPGRADN_CDGRAD_00001 
	PRIMARY KEY( CDGRAD ) ; 
  
ALTER TABLE MAIRIE.SPPRIM 
	ADD CONSTRAINT MAIRIE.Q_MAIRIE_SPPRIM_NOMATR_00001 
	PRIMARY KEY( NOMATR , NORUBR , DATDEB ) ; 
  
ALTER TABLE MAIRIE.SPRUBR 
	ADD CONSTRAINT MAIRIE.Q_MAIRIE_SPRUBR_NORUBR_00001 
	PRIMARY KEY( NORUBR ) ; 
  
ALTER TABLE MAIRIE.SISERV 
	ADD CONSTRAINT MAIRIE.Q_MAIRIE_SISERV_SERVI_00001 
	UNIQUE( SERVI ) ; 