CREATE SEQUENCE SIRH.NUM_REF_MAIRIE
START WITH 1
INCREMENT BY 1
NO MAXVALUE
NO CYCLE
NO CACHE;

CREATE SEQUENCE SIRH.NUM_CONTRAT_SEQ
START WITH 1
INCREMENT BY 1
NO MAXVALUE
NO CYCLE
NO CACHE;

--CREATE SEQUENCE SIRH.NUM_ORDRE_ACTIVITE
--START WITH 1
--INCREMENT BY 1
--NO MAXVALUE
--NO CYCLE
--NO CACHE;

--CONTRAT ??