drop table sirh.PRIME_POINTAGE;
drop table sirh.PRIME_POINTAGE_FP;
drop table sirh.PRIME_POINTAGE_AFF;

create table SIRH.PRIME_POINTAGE_AFF
(
NUM_RUBRIQUE INTEGER,
ID_AFFECTATION INTEGER not null,
constraint SIRH.PK_PRIME_POINTAGE_AFF
primary key (NUM_RUBRIQUE, ID_AFFECTATION),
constraint SIRH.FK_PRIME_POINTAGE_AFF
foreign key (ID_AFFECTATION)
references SIRH.AFFECTATION (ID_AFFECTATION)
);


create table SIRH.PRIME_POINTAGE_FP
(
NUM_RUBRIQUE INTEGER,
ID_FICHE_POSTE INTEGER not null,
constraint SIRH.PK_PRIME_POINTAGE_FP
primary key ( NUM_RUBRIQUE,ID_FICHE_POSTE),
constraint SIRH.FK_PRIME_POINTAGE_FP
foreign key (ID_FICHE_POSTE)
references SIRH.FICHE_POSTE (ID_FICHE_POSTE)
);




