----------------------------------------------------------------
-- RECETTE
----------------------------------------------------------------
create table SIRH2.AVCT_DETACHE
(
   ID_AVCT INTEGER not null GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE),
   ID_AGENT INTEGER not null,
   ID_MOTIF_AVCT INTEGER ,
   DIRECTION_SERVICE VARCHAR(10),
   SECTION_SERVICE VARCHAR(10),
   FILIERE VARCHAR(50),
   GRADE VARCHAR(10),
   ID_NOUV_GRADE CHAR(4),
   ANNEE INTEGER not null,
   CDCADR CHAR(1),
   BM_ANNEE INTEGER,
   BM_MOIS INTEGER,
   BM_JOUR INTEGER,
   ACC_ANNEE INTEGER,
   ACC_MOIS INTEGER,
   ACC_JOUR INTEGER,
   NOUV_BM_ANNEE INTEGER,
   NOUV_BM_MOIS INTEGER,
   NOUV_BM_JOUR INTEGER,
   NOUV_ACC_ANNEE INTEGER,
   NOUV_ACC_MOIS INTEGER,
   NOUV_ACC_JOUR INTEGER,
   IBAN VARCHAR(50),
   INM INTEGER,
   INA INTEGER,
   NOUV_IBAN VARCHAR(50),
   NOUV_INM INTEGER,
   NOUV_INA INTEGER,   
   DATE_GRADE DATE,
   PERIODE_STANDARD NUMERIC(2),
   DATE_AVCT_MOY DATE,
   NUM_ARRETE VARCHAR(8),
   DATE_ARRETE DATE,      
   ETAT CHAR(1) not null,
   CODE_CATEGORIE INTEGER,   
   CARRIERE_SIMU CHAR(1) , 
   DATE_VERIF_SGC DATE ,
   HEURE_VERIF_SGC VARCHAR(5) ,
   USER_VERIF_SGC VARCHAR(7),  
   DATE_VERIF_SEF DATE ,
   HEURE_VERIF_SEF VARCHAR(5) ,
   USER_VERIF_SEF VARCHAR(7),
   DATE_VERIF_ARR DATE ,
   HEURE_VERIF_ARR VARCHAR(5) ,
   USER_VERIF_ARR VARCHAR(7),  
   DATE_VERIF_ARR_IMPR DATE ,
   HEURE_VERIF_ARR_IMPR VARCHAR(5) ,
   USER_VERIF_ARR_IMPR VARCHAR(7),  
   OBSERVATION_ARR VARCHAR(255),
   REGULARISATION smallint not null default 0,
   AGENT_VDN smallint not null default 1,
   constraint SIRH2.PK_AVCT_DETACHE
   primary key (ID_AVCT),
   constraint SIRH2.FK_AGT_AVCT_DETACHE
         foreign key (ID_AGENT)
         references SIRH2.AGENT (ID_AGENT),
   constraint SIRH2.FK_NOUV_GRADE_AVCT_DETACHE
         foreign key (ID_NOUV_GRADE)
         references MAIRIE2.SPGRADN (CDGRAD),
   constraint SIRH2.FK_MOTIF_AVCT_DETACHE
         foreign key (ID_MOTIF_AVCT)
         references SIRH2.P_MOTIF_AVCT (ID_MOTIF_AVCT)
);

+ajouter la table dans les droits du user opensirh

----------------------------------------------------------------
-- PROD
----------------------------------------------------------------
create table SIRH.AVCT_DETACHE
(
   ID_AVCT INTEGER not null GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE),
   ID_AGENT INTEGER not null,
   ID_MOTIF_AVCT INTEGER ,
   DIRECTION_SERVICE VARCHAR(10),
   SECTION_SERVICE VARCHAR(10),
   FILIERE VARCHAR(50),
   GRADE VARCHAR(10),
   ID_NOUV_GRADE CHAR(4),
   ANNEE INTEGER not null,
   CDCADR CHAR(1),
   BM_ANNEE INTEGER,
   BM_MOIS INTEGER,
   BM_JOUR INTEGER,
   ACC_ANNEE INTEGER,
   ACC_MOIS INTEGER,
   ACC_JOUR INTEGER,
   NOUV_BM_ANNEE INTEGER,
   NOUV_BM_MOIS INTEGER,
   NOUV_BM_JOUR INTEGER,
   NOUV_ACC_ANNEE INTEGER,
   NOUV_ACC_MOIS INTEGER,
   NOUV_ACC_JOUR INTEGER,
   IBAN VARCHAR(50),
   INM INTEGER,
   INA INTEGER,
   NOUV_IBAN VARCHAR(50),
   NOUV_INM INTEGER,
   NOUV_INA INTEGER,   
   DATE_GRADE DATE,
   PERIODE_STANDARD NUMERIC(2),
   DATE_AVCT_MOY DATE,
   NUM_ARRETE VARCHAR(8),
   DATE_ARRETE DATE,      
   ETAT CHAR(1) not null,
   CODE_CATEGORIE INTEGER,   
   CARRIERE_SIMU CHAR(1) , 
   DATE_VERIF_SGC DATE ,
   HEURE_VERIF_SGC VARCHAR(5) ,
   USER_VERIF_SGC VARCHAR(7),  
   DATE_VERIF_SEF DATE ,
   HEURE_VERIF_SEF VARCHAR(5) ,
   USER_VERIF_SEF VARCHAR(7),
   DATE_VERIF_ARR DATE ,
   HEURE_VERIF_ARR VARCHAR(5) ,
   USER_VERIF_ARR VARCHAR(7),  
   DATE_VERIF_ARR_IMPR DATE ,
   HEURE_VERIF_ARR_IMPR VARCHAR(5) ,
   USER_VERIF_ARR_IMPR VARCHAR(7),  
   OBSERVATION_ARR VARCHAR(255),
   REGULARISATION smallint not null default 0,
   AGENT_VDN smallint not null default 1,
   constraint SIRH.PK_AVCT_DETACHE
   primary key (ID_AVCT),
   constraint SIRH.FK_AGT_AVCT_DETACHE
         foreign key (ID_AGENT)
         references SIRH.AGENT (ID_AGENT),
   constraint SIRH.FK_NOUV_GRADE_AVCT_DETACHE
         foreign key (ID_NOUV_GRADE)
         references MAIRIE.SPGRADN (CDGRAD),
   constraint SIRH.FK_MOTIF_AVCT_DETACHE
         foreign key (ID_MOTIF_AVCT)
         references SIRH.P_MOTIF_AVCT (ID_MOTIF_AVCT)
);

+ajouter la table dans les droits du user opensirh